# Generated by Django 4.0.4 on 2022-10-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=80, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('tags', models.TextField(verbose_name='TAGS')),
                ('documento', models.FileField(upload_to='documentos/', verbose_name='Documento')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destino_documento', to='dependencias.dependencia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estado_documento', to='documentacion.estado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_documento', to='documentacion.grupo')),
                ('inicidor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='iniciador_documento', to='dependencias.dependencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_documento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
