# Generated by Django 3.1.2 on 2022-10-27 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_auto_20221027_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='inicidor',
            new_name='iniciador',
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'doc', 'docx', 'xlsx'])], verbose_name='Documento'),
        ),
    ]
