# Generated by Django 4.0.4 on 2022-10-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('interno', models.IntegerField(verbose_name='Interno')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('encargado', models.CharField(max_length=50, verbose_name='Encargado')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_dependencia', to='dependencias.tipodependencia')),
            ],
        ),
    ]
