# Generated by Django 4.1.2 on 2022-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='encargado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='interno',
            field=models.IntegerField(blank=True, verbose_name='Interno'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefono'),
        ),
    ]
