# Generated by Django 4.0.4 on 2022-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name_plural': 'Historiales'},
        ),
        migrations.AddField(
            model_name='historial',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='tabla',
            field=models.CharField(default='', max_length=50, verbose_name='Tabla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('A', 'ALTA'), ('B', 'BAJA'), ('M', 'MODIFICACION')], max_length=50, verbose_name='Accion'),
        ),
    ]
