# Generated by Django 3.1.2 on 2022-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_historial_options_historial_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
